spring:
  application:
    name: "random-practice"
test:
  random:
    secret: ${random.value}
    number: ${random.int}
    big-number: ${random.long}
    uuid: ${random.uuid}
    number-less-than-ten: ${random.int(10)}
    range-number: ${random.int[1024,65536]}