spring:
  application:
    name: "random-practice-test"
  profiles:
    include: prod
    active: dev

demo:
  duration:
    second: 40d
    millis: 40ms
    minutes: 40

server:
  port: 8081

---
spring:
  profiles: default
server:
  port: 8881
---
spring:
  profiles: dev
server:
  address: 127.0.0.1
  port: 8882
---
spring:
  profiles: prod
server:
  address: 127.0.0.1
  port: 8883
